apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 6
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: marcorezkallah/nti-cicd-project:v1.0
          imagePullPolicy: 'Always'
          ports:
            - containerPort: 80
